compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  basaldev:
    npmAlwaysAuth: true
    npmAuthToken: "${BASALDEV_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
